#!/bin/bash


CMD=/usr/local/nagios/bin/send_nsca
CFG=/usr/local/nagios/etc/send_nsca.cfg

HOST=$1
SRV=$2
RESULT=$3
OUTPUT="$4"
PERF="$5"

printf "%b" "${HOST}\t${SRV}\t${RESULT}\t${OUTPUT}|${PERF}\n" | $CMD -H uat-bastion -c $CFG
